apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: harness-pilot-test-final
  title: Deploy Harness Solutions Factory Test
  description: Smaller Description
  tags:
    - solutions-factory
    - harness
    - hidden
    - management
spec:
  type: solutions-factory
  parameters:
    - title: Deployment Account Details
      required:
        - deployment_account_id
        - deployment_api_key
      properties:
        deployment_account_id:
          title: Deployment Account Number
          description: Enter the Harness account to which the Pilot Light should be
            deployed
          type: string
        deployment_api_key:
          title: Deployment Access Token
          description: Enter the Harness account to which the Pilot Light should be
            deployed
          type: string
          ui:widget: password
          ui:help: Generate a new secret
    - title: Solutions Factory Connection
      properties:
        solutions_factory_details:
          title: Solutions Factory Details
          type: object
          description: |
            ---
            Harness URL : <+variable.account.solutions_factory_endpoint>

            Harness Account : vpCkHKsDSxK9_KYfjCTMKA

            Solutions Factory Org : <+variable.account.solutions_factory_org>

            Solutions Factory Project : <+variable.account.solutions_factory_project>
          properties:
            harness_account_url:
              type: string
              default: <+variable.account.solutions_factory_endpoint>
              ui:widget: hidden
            harness_account_id:
              type: string
              default: vpCkHKsDSxK9_KYfjCTMKA
              ui:widget: hidden
            harness_org_id:
              type: string
              default: <+variable.account.solutions_factory_org>
              ui:widget: hidden
            harness_project_id:
              type: string
              default: <+variable.account.solutions_factory_project>
              ui:widget: hidden
            harness_remote_project_id:
              type: string
              default: Factory_Deployments
              ui:widget: hidden
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
  steps:
    - id: trigger
      name: Simple Pipeline with wait step
      action: trigger:harness-custom-pipeline
      input:
        url: 'https://qa.harness.io/ng/account/Vp0XSI5MSgiF9p8lIIpThg/module/cd/orgs/default/projects/automation/pipelines/TemplateAutomation/pipeline-studio?storeType=INLINE'   
        inputset:
          project_name: 'test'
        apikey: ${{ parameters.token }}
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
